const routes = {
  home: '/',
  following: '/following',
  profile: '/:nickname',
  upload: '/upload',
  search: '/search',
  live: '/live',
  product: '/products',
  productDetail: '/product/:product_slug',
  shopSignin: '/shop/signin',
  shopSignup: '/shop/signup',
  userSignin: '/user/signin',
  userSignup: '/user/signup',
  shopDraft: '/shop/draft',
  shopPublished: '/shop/published',
  shopCreateProduct: '/shop/create/product',
  shopCreateDiscount: '/shop/create/discount',
  shopRestoreDiscount: '/shop/restore/discount',
  shopEditProduct: '/shop/edit/:productID',
  shopHome: '/shop/',
  userCart: '/cart',
  shopDiscounts: '/discounts',
  payment: '/payment/:method',
  thanks: '/thanks',
};

export default routes;
