const routes = {
  home: '/',
  following: '/following',
  profile: '/:nickname',
  upload: '/upload',
  search: '/search',
  live: '/live',
  product: '/products',
  productDetail: '/product/:product_slug',
  shopSignin: '/shop/signin',
  shopSignup: '/shop/signup',
  userSignin: '/user/signin',
  userSignup: '/user/signup',
  shopDraft: '/shop/draft',
  shopPublished: '/shop/published',
  shopOrders: '/shop/orders',
  shopProductVariants: '/shop/create/product-variants',
  shopCreateProductVariants: '/shop/create/product-variants/:slug',
  shopEditVariant: '/shop/variance/edit/:variantID',
  shopCreateProduct: '/shop/create/product',
  shopCreateDiscount: '/shop/create/discount',
  shopRestoreDiscount: '/shop/restore/discount',
  shopEditProduct: '/shop/edit/:productID',
  shopHome: '/shop/',
  shopView: '/shop/:slug',
  userCart: '/cart',
  shopDiscounts: '/discounts',
  payment: '/payment/:method',
  lobby: '/user/lobby',
  shop: '/shop/lobby',
  checkout: '/checkout',
  voucher: '/voucher',
  userChat: '/user/chat/:toID',
  shopChat: '/shop/chat/:toID',
};

export default routes;
